# KNOWLEDGE GRAPH AND TOPOLOGICAL FEATURES

In [1]:
#importing Libraies
import networkx as nx

import numpy as np
import pandas as pd
from numpy import genfromtxt
import collections
from collections import OrderedDict

import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
#%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression,LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,accuracy_score

# TFIDF FEATURES

In [2]:
mainDataDF=pd.read_csv('/content/normalizeddata.csv')
classList=list(mainDataDF['Class'])
mainDataDF.head()

,able,absolutely,access,accommodation,actually,affinia,air,allegro,amalfi,amazing,...,wireless,woman,wonderful,work,working,worst,worth,wrong,year,Class
0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.502231,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0
2,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.485981,0.000000,0.0,0.0,0.0,0
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0
4,0.0,0.0,0.0,0.713792,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.504096,0.000000,0.586531,0.0,0.0,0.0,0

# CALCULATING DISTANCE MEASURE USING COSINE DISTANCE

In [3]:
mainDataDFWoClass=mainDataDF.copy()
mainDataDFWoClass.drop(columns=['Class'],inplace=True)
mainDataDFWoClass

,able,absolutely,access,accommodation,actually,affinia,air,allegro,amalfi,amazing,...,wine,wireless,woman,wonderful,work,working,worst,worth,wrong,year
0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.502231,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
2,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.485981,0.000000,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.713792,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.504096,0.000000,0.586531,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.290177,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
1596,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
1597,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
1598,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0
1599,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.325672,0.0

In [4]:
def self_cosine_vectorized(a):
    dots = a.dot(a.T)
    sqrt_sums = np.sqrt((a**2).sum(1))
    cosine_dists = 1 - (dots/sqrt_sums)/sqrt_sums[:,None]
    np.fill_diagonal(cosine_dists,0)
    return cosine_dists

In [5]:
dist = self_cosine_vectorized(mainDataDFWoClass.values) 
dist

array([[0.        , 0.92693041, 0.96944816, ..., 0.95332115, 0.75599788,
        0.90800656],
       [0.92693041, 0.        , 0.86594725, ..., 0.90705897, 0.90689575,
        0.88060459],
       [0.96944816, 0.86594725, 0.        , ..., 0.87748327, 0.94263335,
        0.92846667],
       ...,
       [0.95332115, 0.90705897, 0.87748327, ..., 0.        , 0.91242704,
        0.88573982],
       [0.75599788, 0.90689575, 0.94263335, ..., 0.91242704, 0.        ,
        0.89735053],
       [0.90800656, 0.88060459, 0.92846667, ..., 0.88573982, 0.89735053,
        0.        ]])

In [6]:
# Converting array into dataframe format
X1 = pd.DataFrame(dist)
X1.head(10)

,0,1,2,3,4,5,6,7,8,9,...,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599
0,0.000000,0.926930,0.969448,0.809427,0.917508,0.917830,0.919344,0.900375,0.911506,0.862823,...,0.914673,0.976512,0.981870,0.945311,0.857368,0.833665,0.932360,0.953321,0.755998,0.908007
1,0.926930,0.000000,0.865947,0.854505,0.799870,0.916436,0.949354,0.825836,0.903402,0.914326,...,0.912343,0.978987,0.960977,0.918436,0.907821,0.923349,0.928465,0.907059,0.906896,0.880605
2,0.969448,0.865947,0.000000,0.932181,0.874531,0.935116,0.939895,0.896506,0.878455,0.881034,...,0.784586,0.973023,0.877079,0.876749,0.887512,0.926073,0.900167,0.877483,0.942633,0.928467
3,0.809427,0.854505,0.932181,0.000000,0.867599,0.811758,0.859554,0.808307,0.796298,0.773142,...,0.869702,0.978353,0.906106,0.868286,0.877842,0.834470,0.894010,0.872200,0.853266,0.842152
4,0.917508,0.799870,0.874531,0.867599,0.000000,0.927587,0.994236,0.744379,0.812239,0.860774,...,0.825890,0.950981,0.900242,0.881149,0.943828,0.876360,0.936045,0.908649,0.911312,0.865035
5,0.917830,0.916436,0.935116,0.811758,0.927587,0.000000,0.957839,0.951740,0.936547,0.894184,...,0.910467,0.971729,0.899174,0.877792,0.983590,0.798309,0.965153,0.904761,0.938997,0.727127
6,0.919344,0.949354,0.939895,0.859554,0.994236,0.957839,0.000000,0.797236,0.894600,0.882884,...,0.839082,1.000000,0.987314,0.859475,0.929033,0.907886,0.972898,0.909349,0.925588,0.917099
7,0.900375,0.825836,0.896506,0.808307,0.744379,0.951740,0.797236,0.000000,0.902791,0.814836,...,0.847859,0.946627,0.884133,0.921380,0.859625,0.875483,0.922643,0.828879,0.864879,0.864271
8,0.911506,0.903402,0.878455,0.796298,0.812239,0.936547,0.894600,0.902791,0.000000,0.884183,...,0.883933,0.996620,0.918459,0.862897,0.896571,0.887853,0.914265,0.925693,0.831628,0.938408
9,0.862823,0.914326,0.881034,0.773142,0.860774,0.894184,0.882884,0.814836,0.884183,0.000000,...,0.887052,0.892176,0.882278,0.902503,0.882335,0.879028,0.903432,0.916342,0.870854,0.876168

In [7]:
# taking average
y = np.average(X1)
y

0.9100232719149948

In [8]:
adjmat_df=X1.copy()

In [9]:
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [10]:
adjmat_df

,0,1,2,3,4,5,6,7,8,9,...,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599
0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1596,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1597,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1598,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1599,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### BUILDING A FIRST GRAPH

In [11]:
adjmat_df.index =adjmat_df.columns

In [12]:
# Create networkx graph object
graphNw = nx.from_pandas_adjacency(adjmat_df,create_using = nx.Graph())
print(nx.info(graphNw))

Graph with 1600 nodes and 724060 edges

In [13]:
edge_connnected=list(graphNw.edges())

In [14]:
print(nx.info(graphNw))

Graph with 1600 nodes and 724060 edges

In [15]:
edge_connnected=list(graphNw.edges())
#edgesDF = pd.DataFrame(edge_connnected)
#edgesDF.to_csv('graphNwEdges.csv', encoding='utf-8',index=False, header=False)

In [16]:
diGraph = nx.DiGraph()
diGraph.add_edges_from(edge_connnected)
print(nx.info(diGraph))

DiGraph with 1600 nodes and 724060 edges

In [17]:
nodeList=list(graphNw.nodes)

In [18]:
degreesList = [graphNw.degree(n) for n in graphNw.nodes()]

### TOPOLOGICAL FEATURE EXTRACTION

In [19]:
in_degreeDict = dict(diGraph.in_degree())

in_degreeDict = collections.OrderedDict(sorted(in_degreeDict.items()))
inDegreeList=list(in_degreeDict.values())

In [20]:
out_degreeDict = dict(diGraph.out_degree())
out_degreeDict=collections.OrderedDict(sorted(out_degreeDict.items()))
outDegreeList=list(out_degreeDict.values())

In [21]:
hubDict,authDict = nx.hits(graphNw)
hubList=list(hubDict.values())
authList=list(authDict.values())

In [22]:
from networkx.algorithms import community
communities = community.greedy_modularity_communities(graphNw)

In [23]:
pip install tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (4.64.1)

In [24]:
from tqdm import tqdm
modularity_dict = {} # Create a blank dictionary
for i,c in tqdm(enumerate(communities)): # Loop through the list of communities, keeping track of the number for the community
    for name in c: # Loop through each person in a community
        modularity_dict[int(name)] = i
modularityDict=collections.OrderedDict(sorted(modularity_dict.items()))
modularityList=list(modularityDict.values())

3it [00:00, 1578.78it/s]

In [25]:
PageRankDict=nx.pagerank(graphNw, alpha=0.85)
PageRankList=list(PageRankDict.values())

In [26]:
triangleList=[]
for node in tqdm(graphNw.nodes()):
    triangleList.append(nx.triangles(graphNw, node))
#triangleList

100%|██████████| 1600/1600 [03:28<00:00,  7.69it/s]

In [27]:
closenessDict=nx.closeness_centrality(graphNw)
closenessList=list(closenessDict.values())

In [28]:
betweennessCentralityDict = nx.betweenness_centrality(graphNw)
betweennessCentralityList=list(betweennessCentralityDict.values())

In [29]:
harmonicCentralityDict=nx.harmonic_centrality(graphNw)
harmonicCentralityList=list(harmonicCentralityDict.values())

In [30]:
eigenvectorDict = nx.eigenvector_centrality(graphNw) 
eigenvectorList=list(eigenvectorDict.values())

In [31]:
graphFeatures_dict = {'Nodes' : nodeList ,'InDegree':inDegreeList,'OutDegree':outDegreeList,'Degree':degreesList, 'WeightedInDegree':inDegreeList,
              'ClosenessCentrality':closenessList,'HarmonicCentrality':harmonicCentralityList,
              'BetweennessCentrality' :betweennessCentralityList,'Authority':authList,'hub':hubList,'Modularity':modularityList,
              'PageRank':PageRankList,'Triangles':triangleList,'EigenvectorCentrality':eigenvectorList,'Class':classList}
graphFeaturesDf = pd.DataFrame.from_dict(graphFeatures_dict)
graphFeaturesDf

,Nodes,InDegree,OutDegree,Degree,WeightedInDegree,ClosenessCentrality,HarmonicCentrality,BetweennessCentrality,Authority,hub,Modularity,PageRank,Triangles,EigenvectorCentrality,Class
0,0,0,1180,1180,0,0.792369,1389.5,0.000471,0.000795,0.000795,1,0.000789,413415,0.031041,1
1,1,1,803,804,1,0.667920,1201.5,0.000160,0.000571,0.000571,0,0.000563,212119,0.022312,0
2,2,1,973,974,1,0.718975,1286.5,0.000289,0.000670,0.000670,0,0.000666,293637,0.026166,0
3,3,1,570,571,1,0.608679,1085.0,0.000068,0.000420,0.000420,1,0.000425,109626,0.016426,0
4,4,1,752,753,1,0.653988,1176.0,0.000141,0.000534,0.000534,1,0.000533,182918,0.020880,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,1595,496,1,497,496,0.592003,1048.0,0.000043,0.000373,0.000373,0,0.000381,87650,0.014569,1
1596,1596,1099,2,1101,1099,0.762518,1350.0,0.000401,0.000745,0.000745,0,0.000742,363221,0.029116,1
1597,1597,821,1,822,821,0.672980,1210.5,0.000175,0.000580,0.000580,1,0.000574,217542,0.022641,1
1598,1598,839,0,839,839,0.677830,1219.0,0.000187,0.000590,0.000590,1,0.000584,223929,0.023049,1
1599,1599,523,0,523,523,0.597757,1061.0,0.000064,0.000380,0.000380,1,0.000398,88754,0.014853,1

In [32]:
graphFeaturesWOClass=graphFeaturesDf.copy()
graphFeaturesWOClass.drop(columns=['Class','Nodes'],inplace=True)
scaler = MinMaxScaler()
scaledGraphFeatures = pd.DataFrame(scaler.fit_transform(graphFeaturesWOClass.values), columns=graphFeaturesWOClass.columns, index=graphFeaturesWOClass.index)
scaledGraphFeatures

,InDegree,OutDegree,Degree,WeightedInDegree,ClosenessCentrality,HarmonicCentrality,BetweennessCentrality,Authority,hub,Modularity,PageRank,Triangles,EigenvectorCentrality
0,0.000000,0.915438,0.801540,0.000000,0.709391,0.801540,0.602993,0.819331,0.819331,0.5,0.797360,0.719262,0.819332
1,0.000778,0.622964,0.479897,0.000778,0.358019,0.479897,0.196574,0.516996,0.516996,0.0,0.472635,0.350241,0.516997
2,0.000778,0.754849,0.625321,0.000778,0.502169,0.625321,0.365638,0.650478,0.650478,0.0,0.620321,0.499682,0.650479
3,0.000778,0.442203,0.280582,0.000778,0.190757,0.280582,0.076668,0.313122,0.313122,0.5,0.274486,0.162349,0.313123
4,0.000778,0.583398,0.436270,0.000778,0.318683,0.436270,0.172488,0.467388,0.467388,0.5,0.429633,0.296709,0.467389
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.385992,0.000776,0.217280,0.385992,0.143673,0.217280,0.044467,0.248798,0.248798,0.0,0.211595,0.122062,0.248799
1596,0.855253,0.001552,0.733961,0.855253,0.625109,0.733961,0.511504,0.752668,0.752668,0.0,0.729715,0.627245,0.752669
1597,0.638911,0.000776,0.495295,0.638911,0.372305,0.495295,0.217174,0.528378,0.528378,0.5,0.488437,0.360183,0.528380
1598,0.652918,0.000000,0.509837,0.652918,0.385998,0.509837,0.231780,0.542505,0.542505,0.5,0.503010,0.371892,0.542506
1599,0.407004,0.000000,0.239521,0.407004,0.159919,0.239521,0.071338,0.258638,0.258638,0.5,0.235584,0.124085,0.258638

In [33]:
#scaledGraphFeatures['Nodes']=nodeList
scaledGraphFeatures['Class']=classList

In [34]:
scaledGraphFeatures.to_csv('graphFeatures1.csv', encoding='utf-8',index=False)

In [35]:
df = pd.read_csv("graphFeatures1.csv")
df.head()

,InDegree,OutDegree,Degree,WeightedInDegree,ClosenessCentrality,HarmonicCentrality,BetweennessCentrality,Authority,hub,Modularity,PageRank,Triangles,EigenvectorCentrality,Class
0,0.000000,0.915438,0.801540,0.000000,0.709391,0.801540,0.602993,0.819331,0.819331,0.5,0.797360,0.719262,0.819332,1
1,0.000778,0.622964,0.479897,0.000778,0.358019,0.479897,0.196574,0.516996,0.516996,0.0,0.472635,0.350241,0.516997,0
2,0.000778,0.754849,0.625321,0.000778,0.502169,0.625321,0.365638,0.650478,0.650478,0.0,0.620321,0.499682,0.650479,0
3,0.000778,0.442203,0.280582,0.000778,0.190757,0.280582,0.076668,0.313122,0.313122,0.5,0.274486,0.162349,0.313123,0
4,0.000778,0.583398,0.436270,0.000778,0.318683,0.436270,0.172488,0.467388,0.467388,0.5,0.429633,0.296709,0.467389,0

In [36]:
df.shape

(1600, 14)

In [37]:
y = df['Class']

In [38]:
x = df.drop(['Class'], axis = 1)

In [39]:
x.shape

(1600, 13)

In [40]:
y.shape

(1600,)

In [41]:
x.head()

,InDegree,OutDegree,Degree,WeightedInDegree,ClosenessCentrality,HarmonicCentrality,BetweennessCentrality,Authority,hub,Modularity,PageRank,Triangles,EigenvectorCentrality
0,0.000000,0.915438,0.801540,0.000000,0.709391,0.801540,0.602993,0.819331,0.819331,0.5,0.797360,0.719262,0.819332
1,0.000778,0.622964,0.479897,0.000778,0.358019,0.479897,0.196574,0.516996,0.516996,0.0,0.472635,0.350241,0.516997
2,0.000778,0.754849,0.625321,0.000778,0.502169,0.625321,0.365638,0.650478,0.650478,0.0,0.620321,0.499682,0.650479
3,0.000778,0.442203,0.280582,0.000778,0.190757,0.280582,0.076668,0.313122,0.313122,0.5,0.274486,0.162349,0.313123
4,0.000778,0.583398,0.436270,0.000778,0.318683,0.436270,0.172488,0.467388,0.467388,0.5,0.429633,0.296709,0.467389

###  TRAIN TEST SPLIT

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=7, stratify=y)

### BASELINE MODEL

In [43]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[160   0]
 [160   0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       160
           1       0.00      0.00      0.00       160

    accuracy                           0.50       320
   macro avg       0.25      0.50      0.33       320
weighted avg       0.25      0.50      0.33       320

accuracy_score:  0.5

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [44]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[89 71]
 [83 77]]
              precision    recall  f1-score   support

           0       0.52      0.56      0.54       160
           1       0.52      0.48      0.50       160

    accuracy                           0.52       320
   macro avg       0.52      0.52      0.52       320
weighted avg       0.52      0.52      0.52       320

accuracy_score:  0.51875

### CROSS VALIDATION

In [45]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
cv = KFold(n_splits=10, random_state=1, shuffle=True)
kf = KFold(n_splits=10)

In [46]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
scores = cross_val_score(lsvm, x, y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.535

In [47]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
scores = cross_val_score(pa, x, y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.684375

In [48]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression(max_iter=10000) 
scores = cross_val_score(log, x, y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.531875

In [49]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300)
scores = cross_val_score(rf, x, y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.9775

In [50]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.21.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.7.3)

In [51]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
scores = cross_val_score(xgbc, x, y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.976875

## Conclusion: Using XGboost classifier, the accuracy is 98%