# FAKE REVIEW NODE EMBEDDING

In [135]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: stellargraph in /usr/local/lib/python3.7/dist-packages (1.2.1)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (3.2.2)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (1.21.6)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (1.0.2)
Requirement already satisfied: tensorflow>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (2.9.2)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (2.6.3)
Requirement already satisfied: gensim>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (3.6.0)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (1.3.5)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from stellargraph) (1.7.3)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from gensim>=3.4.0->stellargraph) (1.15.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim>=3.4.0->stellargraph) (5.2.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->stellargraph) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->stellargraph) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->stellargraph) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2->stellargraph) (3.0.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=2.2->stellargraph) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->stellargraph) (2022.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20->stellargraph) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20->stellargraph) (3.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (21.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (57.4.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.3.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.17.3)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.0.1)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.27.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.2.0)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.12)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.3.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.6.3)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.1.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.50.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (14.0.6)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.4.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.1.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from astunparse>=1.6.0->tensorflow>=2.1.0->stellargraph) (0.37.1)
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/dist-packages (from h5py>=2.9.0->tensorflow>=2.1.0->stellargraph) (1.5.2)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.4.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.35.0)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.23.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.9)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.13.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.9.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.2.2)

In [136]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [137]:
#importing libraries
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import statistics
import math
import os
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.metrics import confusion_matrix
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

import re
pd.set_option('max_colwidth', 800)


#importing Libraies
import networkx as nx
import matplotlib.pyplot as plt
from numpy import genfromtxt
import collections
from collections import OrderedDict

import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression,LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [138]:
#loading dataset
df=pd.read_csv('/content/deceptive.csv')
df.head()

,deceptive,hotel,polarity,source,text,Class
0,truthful,conrad,positive,TripAdvisor,"We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n",1
1,truthful,hyatt,positive,TripAdvisor,"Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n",1
2,truthful,hyatt,positive,TripAdvisor,"This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...",1
3,truthful,omni,positive,TripAdvisor,"The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n",1
4,truthful,hyatt,positive,TripAdvisor,"I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Michigan Avenue shopping district. \n",1

In [139]:
d = []
for i in range(1600):
    s = i+1
    d.append(s)

In [140]:
d

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

In [141]:
df.insert(0, 'Index', d)
df.head()

,Index,deceptive,hotel,polarity,source,text,Class
0,1,truthful,conrad,positive,TripAdvisor,"We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n",1
1,2,truthful,hyatt,positive,TripAdvisor,"Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n",1
2,3,truthful,hyatt,positive,TripAdvisor,"This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...",1
3,4,truthful,omni,positive,TripAdvisor,"The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n",1
4,5,truthful,hyatt,positive,TripAdvisor,"I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Michigan Avenue shopping district. \n",1

In [142]:
df.shape

(1600, 7)

In [143]:
df['Class'].value_counts()

1    800
0    800
Name: Class, dtype: int64

In [144]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,Index,deceptive,hotel,polarity,source,text,Class
0,419,deceptive,fairmont,positive,MTurk,"The Fairmont Chicago Millenium Park Hotel provides a rich, beautiful, cultured atmosphere. During my stay, I felt like royalty. With unparalleled design schemes and beautiful, tranquil views, the mood during my entire stay was one of bliss. The guest services department was second-to-none. The staff throughout the hotel were obviously concerned with pleasing the customer and making my stay as wonderful as possible. When dealing with a staff member at Fairmont, I felt as if I were the only guest in the place. The food and drink selections were vast and fit for a king. I will definitely recommend Fairmont Chicago Millenium Park to my friends and colleagues. I will also greatly look forward to my next stay.\n",0
1,301,truthful,hilton,positive,TripAdvisor,"I took the wife and kids to Chicago for one last fling before school started back up. When I checked in, the staff was very attentive, I showed a little consideration for the friendly attitude (small tip) and was upgraded to a huge upper floor room complete with a bar! I didn't get the 'Priceline' glare and it paid off for all involved. The air and water show was underway on the lake front, and we had planes flying over our room. The kids thought it was great. That night we had a great view of the fireworks at Navy Pier. The Sunday morning breakfast buffet at the hotel was very good and the price was not out of reason. The conceirge was very knowledgeable and very friendly. It was one of the best times we ever had in Chicago. \n",1
2,1021,truthful,talbott,negative,Web,"I selected the Talbott after 3 hrs comparing hotels online. We have had wonderful experiences with boutiques (Monaco, Allegro) and assumed this would be comparable. Good points: the lobby is beautiful, and one staff member took roses I bought for my wife and arranged them nicely. The many problems: When my wife called with a question on our arrival day, the agent could find no reservation -- 15 mins later she was transferred to another person who found the record instantly. When we arrived, the lobby was stuffed with students; nobody tried to manage the group, several of whom pushed ahead to the check-in desk. We left our bags and went out for 2 hrs so we could check in with less hassle. We finally were checked in, after waiting 15 mins while the confused desk clerk searched for rooms....",1
3,697,deceptive,hilton,positive,MTurk,"Our stay at the Hilton Chicago was a pleasure from arrival to departure. The staff was super friendly and helpful, the room was very clean and the location was fantastic. The walking track was an especially nice touch. Highly recommended!\n",0
4,287,truthful,hilton,positive,TripAdvisor,"Thirty years ago, we had a tiny 'room' and indifferent service. This time, the service was superb and friendly throughout, with special commendation for the waiters and waitresses at the coffee shop, the door and bell persons, and the hilton honors person at the front desk. They even lowered our price (to moderately high) when we inquired a few days before our stay. When we want to stay south of the river downtown, we will be back \n",1

In [145]:
# dropping unnecessary columns. 
df.drop(['deceptive', 'hotel', 'polarity', 'source'], axis = 1, inplace=True)
df.head()

,Index,text,Class
0,419,"The Fairmont Chicago Millenium Park Hotel provides a rich, beautiful, cultured atmosphere. During my stay, I felt like royalty. With unparalleled design schemes and beautiful, tranquil views, the mood during my entire stay was one of bliss. The guest services department was second-to-none. The staff throughout the hotel were obviously concerned with pleasing the customer and making my stay as wonderful as possible. When dealing with a staff member at Fairmont, I felt as if I were the only guest in the place. The food and drink selections were vast and fit for a king. I will definitely recommend Fairmont Chicago Millenium Park to my friends and colleagues. I will also greatly look forward to my next stay.\n",0
1,301,"I took the wife and kids to Chicago for one last fling before school started back up. When I checked in, the staff was very attentive, I showed a little consideration for the friendly attitude (small tip) and was upgraded to a huge upper floor room complete with a bar! I didn't get the 'Priceline' glare and it paid off for all involved. The air and water show was underway on the lake front, and we had planes flying over our room. The kids thought it was great. That night we had a great view of the fireworks at Navy Pier. The Sunday morning breakfast buffet at the hotel was very good and the price was not out of reason. The conceirge was very knowledgeable and very friendly. It was one of the best times we ever had in Chicago. \n",1
2,1021,"I selected the Talbott after 3 hrs comparing hotels online. We have had wonderful experiences with boutiques (Monaco, Allegro) and assumed this would be comparable. Good points: the lobby is beautiful, and one staff member took roses I bought for my wife and arranged them nicely. The many problems: When my wife called with a question on our arrival day, the agent could find no reservation -- 15 mins later she was transferred to another person who found the record instantly. When we arrived, the lobby was stuffed with students; nobody tried to manage the group, several of whom pushed ahead to the check-in desk. We left our bags and went out for 2 hrs so we could check in with less hassle. We finally were checked in, after waiting 15 mins while the confused desk clerk searched for rooms....",1
3,697,"Our stay at the Hilton Chicago was a pleasure from arrival to departure. The staff was super friendly and helpful, the room was very clean and the location was fantastic. The walking track was an especially nice touch. Highly recommended!\n",0
4,287,"Thirty years ago, we had a tiny 'room' and indifferent service. This time, the service was superb and friendly throughout, with special commendation for the waiters and waitresses at the coffee shop, the door and bell persons, and the hilton honors person at the front desk. They even lowered our price (to moderately high) when we inquired a few days before our stay. When we want to stay south of the river downtown, we will be back \n",1

In [146]:
# Cleaning Raw tweets
def clean_text(text):
    
    #remove emails
    text = ' '.join([i for i in text.split() if '@' not in i])
    
    #remove web address
    text = re.sub('http[s]?://\S+', '', text)

    #remove brackets and parantheses (and removing the text inside the brackets and parantheses)
    text = re.sub("[\(\[].*?[\)\]]", "", text)

    #remove punctuations
    text = re.sub(r'[^\w\s]', ' ', text)
    
    #Filter to allow only alphabets and numbers
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    
    #Remove Unicode characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    #remove double spaces 
    text = re.sub('\s+', ' ', text)
    
    return text

In [147]:
# applying that into function.
df["clean_text"] = df['text'].apply(lambda x: clean_text(x))
df.head(10)

,Index,text,Class,clean_text
0,419,"The Fairmont Chicago Millenium Park Hotel provides a rich, beautiful, cultured atmosphere. During my stay, I felt like royalty. With unparalleled design schemes and beautiful, tranquil views, the mood during my entire stay was one of bliss. The guest services department was second-to-none. The staff throughout the hotel were obviously concerned with pleasing the customer and making my stay as wonderful as possible. When dealing with a staff member at Fairmont, I felt as if I were the only guest in the place. The food and drink selections were vast and fit for a king. I will definitely recommend Fairmont Chicago Millenium Park to my friends and colleagues. I will also greatly look forward to my next stay.\n",0,The Fairmont Chicago Millenium Park Hotel provides a rich beautiful cultured atmosphere During my stay I felt like royalty With unparalleled design schemes and beautiful tranquil views the mood during my entire stay was one of bliss The guest services department was second to none The staff throughout the hotel were obviously concerned with pleasing the customer and making my stay as wonderful as possible When dealing with a staff member at Fairmont I felt as if I were the only guest in the place The food and drink selections were vast and fit for a king I will definitely recommend Fairmont Chicago Millenium Park to my friends and colleagues I will also greatly look forward to my next stay
1,301,"I took the wife and kids to Chicago for one last fling before school started back up. When I checked in, the staff was very attentive, I showed a little consideration for the friendly attitude (small tip) and was upgraded to a huge upper floor room complete with a bar! I didn't get the 'Priceline' glare and it paid off for all involved. The air and water show was underway on the lake front, and we had planes flying over our room. The kids thought it was great. That night we had a great view of the fireworks at Navy Pier. The Sunday morning breakfast buffet at the hotel was very good and the price was not out of reason. The conceirge was very knowledgeable and very friendly. It was one of the best times we ever had in Chicago. \n",1,I took the wife and kids to Chicago for one last fling before school started back up When I checked in the staff was very attentive I showed a little consideration for the friendly attitude and was upgraded to a huge upper floor room complete with a bar I didn t get the Priceline glare and it paid off for all involved The air and water show was underway on the lake front and we had planes flying over our room The kids thought it was great That night we had a great view of the fireworks at Navy Pier The Sunday morning breakfast buffet at the hotel was very good and the price was not out of reason The conceirge was very knowledgeable and very friendly It was one of the best times we ever had in Chicago
2,1021,"I selected the Talbott after 3 hrs comparing hotels online. We have had wonderful experiences with boutiques (Monaco, Allegro) and assumed this would be comparable. Good points: the lobby is beautiful, and one staff member took roses I bought for my wife and arranged them nicely. The many problems: When my wife called with a question on our arrival day, the agent could find no reservation -- 15 mins later she was transferred to another person who found the record instantly. When we arrived, the lobby was stuffed with students; nobody tried to manage the group, several of whom pushed ahead to the check-in desk. We left our bags and went out for 2 hrs so we could check in with less hassle. We finally were checked in, after waiting 15 mins while the confused desk clerk searched for rooms....",1,I selected the Talbott after hrs comparing hotels online We have had wonderful experiences with boutiques and assumed this would be comparable Good points the lobby is beautiful and one staff member took roses I bought for my wife and arranged them nicely The many problems When my wife called with a question on our arrival day the agent could find no reservation mins later she was transferred to another person who found the record instantly When we arrived the lobby was stuffed with students nobody tried to manage the group several of whom pushed ahead to the check in desk We left our bags and went out for hrs so we could check in with less hassle We finally were checked in after waiting mins while the confused desk clerk searched for rooms When we got there our room had not been made ...
3,697,"Our stay at the Hilton Chicago was a pleasure from arrival to departure. The staff was super friendly and helpful, the room was very clean and the location was fantastic. The walking track was an especially nice touch. Highly recommended!\n",0,Our stay at the Hilton Chicago was a pleasure from arrival to departure The staff was super friendly and helpful the room was very clean and the location was fantastic The walking track was an especially nice touch Highly recommended
4,287,"Thirty years ago, we had a tiny 'room' and indifferent service. This time, the service was superb and friendly throughout, with special commendation for the waiters and waitresses at the coffee shop, the door and bell persons, and the hilton honors person at the front desk. They even lowered our price (to moderately high) when we inquired a few days before our stay. When we want to stay south of the river downtown, we will be back \n",1,Thirty years ago we had a tiny room and indifferent service This time the service was superb and friendly throughout with special commendation for the waiters and waitresses at the coffee shop the door and bell persons and the hilton honors person at the front desk They even lowered our price when we inquired a few days before our stay When we want to stay south of the river downtown we will be back
5,1273,"What a disappointment this hotel was. First, the checkin desk was understaffed and we had to wait forever to get through the line to check in. When we finally got up to our room, we opened the door and found someone else was already in it! Yes, the front desk clerk actually checked us into an occupied room and basically gave us a key to someone else's room. We went back to the clerk who checked us in (skipping the still present line, which got us annoyed stares from the other people waiting) and told him the problem. However, he was already helping another guest checkin and made us wait until he was done with that person before helping us. He did apologize for the mix up and then went into the back room to find out what to do. This took a *very* long time. It was a good 10-15 minutes u...",0,What a disappointment this hotel was First the checkin desk was understaffed and we had to wait forever to get through the line to check in When we finally got up to our room we opened the door and found someone else was already in it Yes the front desk clerk actually checked us into an occupied room and basically gave us a key to someone else s room We went back to the clerk who checked us in and told him the problem However he was already helping another guest checkin and made us wait until he was done with that person before helping us He did apologize for the mix up and then went into the back room to find out what to do This took a very long time It was a good minutes until he came back He said there were no more rooms available of the type we had booked and the only ones they had...
6,883,I booked a hotel room for 4 nights at this hotel through an online vendor. After booking the hotel room I contacted the hotel to request a room with 2 beds. I was told in 3 different conversations with hotel personnel that I would have a room with 2 double beds. When I arrived I was given a King sized bed and was told that there was nothing the hotel could do for myself and my 3 guests. Apparently the hotel management saw no problem with 4 people sleeping in 1 bed. The staff was completely unaccomodating. To add insult to injury we met other guests that had obtained a room with 2 beds by just walking in off the street the day after we checked in. I would not recommend this hotel to anyone. The customer service is well below what is acceptable. The location of the hotel is great but the...,1,I booked a hotel room for nights at this hotel through an online vendor After booking the hotel room I contacted the hotel to request a room with beds I was told in different conversations with hotel personnel that I would have a room with double beds When I arrived I was given a King sized bed and was told that there was nothing the hotel could do for myself and my guests Apparently the hotel management saw no problem with people sleeping in bed The staff was completely unaccomodating To add insult to injury we met other guests that had obtained a room with beds by just walking in off the street the day after we checked in I would not recommend this hotel to anyone The customer service is well below what is acceptable The location of the hotel is great but there are many other hotels ...
7,1288,"I booked a room at Swissotel Chicago because I thought the price was reasonable, and at the base price it was; however, it ended up costing more than I had planned for, as you have to pay for parking and other amenities. The service was not very good, considering they market themselves as a luxury hotel. There was no one there to help us bring in our bags when we had a difficult time doing so, and the staff were cold. All in all, I would say it was an average experience... not luxurious like they claim it to be.\n",0,I booked a room at Swissotel Chicago because I thought the price was reasonable and at the base price it was however it ended up costing more than I had planned for as you have to pay for parking and other amenities The service was not very good considering they market themselves as a luxury hotel There was no one there to help us bring in our bags when we had a difficult time doing so and the staff were cold All in all I would say it was an average experience not luxurious like they claim it to be
8,216,I stayed here August 20 through 23rd with my sixteen year old son and we thoroughly enjoyed this hotel. The price was very reasonable for a hotel located right on Michigan Avenue. The front desk and concierge service was excellent and enhanced our stay by making it easy for us to plan fun activities. The John Entwistle theme on our floor was a nice touch. Any of you single fathers out there can appreciate how difficult it can be to take a fun affordable vacation with your children and The Hard Rock Hotel in Chicago really helped me accomplish just that! \n,1,I stayed here August through rd with my sixteen year old son and we thoroughly enjoyed this hotel The price was very reasonable for a hotel located right on Michigan Avenue The front desk and concierge service was excellent and enhanced our stay by making it easy for us to plan fun activities The John Entwistle theme on our floor was a nice touch Any of you single fathers out there can appreciate how difficult it can be to take a fun affordable vacation with your children and The Hard Rock Hotel in Chicago really helped me accomplish just that
9,829,"The Conrad Hilton recently took over this property from the failed Meridian Hotel. It seems that the Conrad has inherited a hotel property that just doesn't work. The entrance is very difficult to find. There are only two elevators to take you up to the lobby. As a result, there was often a line waiting for them. The same problem affects the guest room elevators located beyond the registration area. If you go in and out of the hotel more than a couple of times during your stay, you will find the poor elevator layout annoying. The King room is what I would consider small compared to other Chicago hotels. Although I like modern design, the room was quite stark and cold. It was also showing quite a bit of wear and tear. The bathroom was the best part. Has anyone from management tried to s...",1,The Conrad Hilton recently took over this property from the failed Meridian Hotel It seems that the Conrad has inherited a hotel property that just doesn t work The entrance is very difficult to find There are only two elevators to take you up to the lobby As a result there was often a line waiting for them The same problem affects the guest room elevators located beyond the registration area If you go in and out of the hotel more than a couple of times during your stay you will find the poor elevator layout annoying The King room is what I would consider small compared to other Chicago hotels Although I like modern design the room was quite stark and cold It was also showing quite a bit of wear and tear The bathroom was the best part Has anyone from management tried to sit in the chai...

In [148]:
# dropping the uncleaned text column "text"
df = df.drop(['text'], axis=1)

In [149]:
# renaming the column
df.rename(columns = {'clean_text':'text'}, inplace = True)
df.head()

,Index,Class,text
0,419,0,The Fairmont Chicago Millenium Park Hotel provides a rich beautiful cultured atmosphere During my stay I felt like royalty With unparalleled design schemes and beautiful tranquil views the mood during my entire stay was one of bliss The guest services department was second to none The staff throughout the hotel were obviously concerned with pleasing the customer and making my stay as wonderful as possible When dealing with a staff member at Fairmont I felt as if I were the only guest in the place The food and drink selections were vast and fit for a king I will definitely recommend Fairmont Chicago Millenium Park to my friends and colleagues I will also greatly look forward to my next stay
1,301,1,I took the wife and kids to Chicago for one last fling before school started back up When I checked in the staff was very attentive I showed a little consideration for the friendly attitude and was upgraded to a huge upper floor room complete with a bar I didn t get the Priceline glare and it paid off for all involved The air and water show was underway on the lake front and we had planes flying over our room The kids thought it was great That night we had a great view of the fireworks at Navy Pier The Sunday morning breakfast buffet at the hotel was very good and the price was not out of reason The conceirge was very knowledgeable and very friendly It was one of the best times we ever had in Chicago
2,1021,1,I selected the Talbott after hrs comparing hotels online We have had wonderful experiences with boutiques and assumed this would be comparable Good points the lobby is beautiful and one staff member took roses I bought for my wife and arranged them nicely The many problems When my wife called with a question on our arrival day the agent could find no reservation mins later she was transferred to another person who found the record instantly When we arrived the lobby was stuffed with students nobody tried to manage the group several of whom pushed ahead to the check in desk We left our bags and went out for hrs so we could check in with less hassle We finally were checked in after waiting mins while the confused desk clerk searched for rooms When we got there our room had not been made ...
3,697,0,Our stay at the Hilton Chicago was a pleasure from arrival to departure The staff was super friendly and helpful the room was very clean and the location was fantastic The walking track was an especially nice touch Highly recommended
4,287,1,Thirty years ago we had a tiny room and indifferent service This time the service was superb and friendly throughout with special commendation for the waiters and waitresses at the coffee shop the door and bell persons and the hilton honors person at the front desk They even lowered our price when we inquired a few days before our stay When we want to stay south of the river downtown we will be back

In [150]:
import spacy
#loading the english language small model of spacy
en = spacy.load('en_core_web_sm')
sw_spacy = en.Defaults.stop_words
print(sw_spacy)

{'yourself', 'has', 'nine', 'some', 'each', 'six', 'only', 'call', 'except', 'them', 'hers', 'than', 'who', 'of', 'together', 'are', 'while', 'these', 'no', 'us', 'due', 'for', 'yet', 'beside', 'me', 'name', 'not', 'others', 'why', 'regarding', 'he', 'this', 'being', 'should', 'amount', 'could', '‘ll', 'both', 'ours', 'had', 'although', 'fifteen', 'indeed', 'your', 'else', 'give', "n't", 'therefore', 'keep', 'because', 'moreover', 'almost', 'front', 'along', 'used', 'hence', 'whence', 'part', 'now', 'under', 'even', 'nevertheless', 'forty', 'we', 'anyone', 'sometime', 'thence', 'were', 'always', 'everything', 'in', "'ll", 'mostly', 'someone', 'beforehand', 'mine', 'further', 'less', 'among', 'own', 'via', 'rather', 'all', 'out', 'just', 'several', 'which', 'somewhere', 'get', 'full', 'nowhere', 'please', 'former', 'back', 'one', 'every', 'there', 'whereby', 'say', 'already', 'become', 'same', 'yourselves', 'whither', 'meanwhile', 'can', 'alone', 'per', 'anyway', 'too', 'much', 'other', 'below', 'unless', 'him', 'using', 'toward', 'have', 'would', 'thereby', 'you', 'often', 'eight', 'latter', 'since', 'before', 'eleven', 'fifty', 'becoming', '’ll', 'nor', 'to', '’m', 'enough', 'whole', 'whenever', 'might', 'whose', 'it', 'somehow', 'thereafter', 'with', 'top', 'something', 'when', '’s', 'three', 'really', 'her', 'noone', 'seeming', 'from', 'during', 'into', 'through', 'take', 'am', 'but', 'as', 'i', 'put', 'few', 'perhaps', 'whom', 'will', 'after', 'also', 'make', 'how', 'whether', 'twenty', 'everywhere', 'elsewhere', 'upon', 'what', 'amongst', '‘ve', 'last', '‘m', 'nothing', 'herein', 'everyone', 'seems', 'until', 'may', 'onto', 'such', 'becomes', 'a', 'next', 'none', 'if', 'within', 'least', 'anything', 'seemed', 'our', '’d', 'whereafter', 'ten', 'ever', 'on', 'then', 'however', 'move', '‘s', 'doing', 'whereupon', 'whereas', "'re", 'very', 'be', 'the', 'its', 'neither', 'various', 'against', 'must', "'s", 'more', "'d", 'she', "'m", 'was', 'towards', 'itself', 'seem', 'been', 'off', 'whatever', 'serious', '’ve', 'where', 'their', 'whoever', 'latterly', 'anyhow', 'hereupon', 'over', 'yours', 'hereafter', 'first', 'at', 'between', 'empty', 'his', 'without', "'ve", 'does', 'around', 'n’t', 'myself', 'up', 'sixty', 'five', 'never', 'my', 'here', 'hundred', 'above', 'once', 'namely', 'anywhere', 'again', 'is', 'afterwards', 'herself', '’re', 'hereby', 'wherein', 'another', 'quite', 'they', 'themselves', 'thereupon', 'still', 'show', 'cannot', 'bottom', 'most', 'sometimes', 'though', 'or', 'and', 'otherwise', 'two', 'thru', 'many', 'any', 'by', 'across', 'beyond', 'four', 'side', 'besides', 'an', '‘re', 'either', 'made', 'therein', 'third', 'behind', 'thus', 'twelve', 'nobody', 'himself', 'done', 'formerly', 'n‘t', 'that', 'became', 'well', 'ca', 'wherever', 'did', 'about', 'ourselves', '‘d', 'see', 'do', 'throughout', 're', 'so', 'those', 'down', 'go'}

In [151]:
import nltk
from nltk.corpus import stopwords
sw_nltk = stopwords.words('english')
print(sw_nltk)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [152]:
sw_nltk.extend(['th','stay'])
print(len(sw_nltk))

181

In [153]:
# preprocessing the data (removing stopwords, convert the sentence to lower case, and also applying lemmatization to get meaningful words )
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
#stop_words = set(stopwords.words('english'))
ps=PorterStemmer()
wnl=WordNetLemmatizer()
def clean_lemma(review):
    review = review.lower()
    review = review.split()
    review = [wnl.lemmatize(word) for word in review if word not in sw_nltk]
    review = [wnl.lemmatize(word) for word in review if word not in sw_spacy]
    review = ' '.join(review)
    return review

In [154]:
# using lemmatization
df['text']=df['text'].apply(clean_lemma)
df.head()

,Index,Class,text
0,419,0,fairmont chicago millenium park hotel provides rich beautiful cultured atmosphere felt like royalty unparalleled design scheme beautiful tranquil view mood entire bliss guest service department second staff hotel obviously concerned pleasing customer making wonderful possible dealing staff member fairmont felt guest place food drink selection vast fit king definitely recommend fairmont chicago millenium park friend colleague greatly look forward
1,301,1,took wife kid chicago fling school started checked staff attentive showed little consideration friendly attitude upgraded huge upper floor room complete bar priceline glare paid involved air water underway lake plane flying room kid thought great night great view firework navy pier sunday morning breakfast buffet hotel good price reason conceirge knowledgeable friendly best time chicago
2,1021,1,selected talbott hr comparing hotel online wonderful experience boutique assumed comparable good point lobby beautiful staff member took rose bought wife arranged nicely problem wife called question arrival day agent find reservation min later transferred person found record instantly arrived lobby stuffed student tried manage group pushed ahead check desk left bag went hr check le hassle finally checked waiting min confused desk clerk searched room got room guest complained given upgrade room old uninspired chair scuffed closet shelf bowed air conditioner noisy wall lamp loose view construction site movie demand dated expect budget hotel positioning elegant upscale returned evening card reader open main door work staff member admonished u reader fact tried embarrassing standing lobby ...
3,697,0,hilton chicago pleasure arrival departure staff super friendly helpful room clean location fantastic walking track especially nice touch highly recommended
4,287,1,thirty year ago tiny room indifferent service time service superb friendly special commendation waiter waitress coffee shop door bell person hilton honor person desk lowered price inquired day want south river downtown

In [155]:
df1 = df.sort_values(by=['Index'], ascending=True)
df1.head()

,Index,Class,text
1054,1,1,stayed night getaway family thursday triple aaa rate steal floor room complete plasma tv bose stereo voss evian water gorgeous bathroom concierge helpful beat location flaw breakfast pricey service slow table restaurant food good worth wait return heartbeat gem chicago
439,2,1,triple rate upgrade view room le included breakfast voucher great view river lake wrigley bldg tribune bldg major restaurant shopping sightseeing attraction walking distance large room comfortable bed
519,3,1,come little late finally catching review past month dear friend stayed hyatt regency late october night visiting friend husband town hotel perfect imo easy check check lovely clean comfortable room great view city know area pretty convenient downtown chicago attraction dinner went clubing friend division st problem getting cab forth hyatt public transportation right near bother needed cab hotel parking usual chicago expensive able car quickly problem best got rate hotwire downright steal area chicago quality hotel
1175,4,1,omni chicago delivers spaciousness room helpful staff prized location michigan avenue address chicago requires high level quality omni delivers check group people minute staff plentiful recommendation dining event room largest find price range chicago standard room separate living area work desk fitness center free weight weight machine row cardio equipment shared room feel cramped way great property
1269,5,1,asked high floor away elevator got room pleasantly decorated functional clean need lot service pleasant prompt fitness center equipped working order great location end michigan avenue shopping district

In [156]:
df1.reset_index(drop=True, inplace=True)

In [157]:
df1.head()

,Index,Class,text
0,1,1,stayed night getaway family thursday triple aaa rate steal floor room complete plasma tv bose stereo voss evian water gorgeous bathroom concierge helpful beat location flaw breakfast pricey service slow table restaurant food good worth wait return heartbeat gem chicago
1,2,1,triple rate upgrade view room le included breakfast voucher great view river lake wrigley bldg tribune bldg major restaurant shopping sightseeing attraction walking distance large room comfortable bed
2,3,1,come little late finally catching review past month dear friend stayed hyatt regency late october night visiting friend husband town hotel perfect imo easy check check lovely clean comfortable room great view city know area pretty convenient downtown chicago attraction dinner went clubing friend division st problem getting cab forth hyatt public transportation right near bother needed cab hotel parking usual chicago expensive able car quickly problem best got rate hotwire downright steal area chicago quality hotel
3,4,1,omni chicago delivers spaciousness room helpful staff prized location michigan avenue address chicago requires high level quality omni delivers check group people minute staff plentiful recommendation dining event room largest find price range chicago standard room separate living area work desk fitness center free weight weight machine row cardio equipment shared room feel cramped way great property
4,5,1,asked high floor away elevator got room pleasantly decorated functional clean need lot service pleasant prompt fitness center equipped working order great location end michigan avenue shopping district

### FEATURE EXTRACTION

In [158]:
x = df1['text']
y = df1['Class']

In [159]:
y

0       1
1       1
2       1
3       1
4       1
       ..
1595    0
1596    0
1597    0
1598    0
1599    0
Name: Class, Length: 1600, dtype: int64

In [160]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
corpii=cv.fit_transform(x)

In [161]:
feature_names = cv.get_feature_names()
#feature_names

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [162]:
len(feature_names)

7905

In [163]:
u1 = pd.DataFrame(corpii.toarray(), columns=feature_names)
u1.head()

,aaa,aaahed,aback,abassador,abd,ability,able,abound,abrupt,abruptly,...,yucky,yummo,yummy,yunan,yup,zagat,zest,zipped,zone,zoo
0,0.217034,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.090437,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### FEATURE SELECTION

In [164]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# Two features with highest chi-squared statistics are selected
chi2_features = SelectKBest(chi2, k = 2000)
X_kbest_features = chi2_features.fit_transform(u1, y)

In [165]:
chi_support = chi2_features.get_support()

In [166]:
chi_feature = u1.loc[:,chi_support].columns.tolist()

In [167]:
X_kbest_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [168]:
u3 = pd.DataFrame(X_kbest_features, columns = chi_feature)
u3.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yellow,yep,yes,yo,yoga,young,youve,yr,yummy,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [169]:
X1 = pd.concat([u3, y], axis=1)
X1.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yep,yes,yo,yoga,young,youve,yr,yummy,zone,Class
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [170]:
u3.head()

,absent,absolute,absolutely,absurd,accept,accepted,accesible,accomadating,accomidations,accommodated,...,yellow,yep,yes,yo,yoga,young,youve,yr,yummy,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [171]:
df1['Class'].value_counts()

1    800
0    800
Name: Class, dtype: int64

In [172]:
#node_Class
node_Class = df1["Class"]

### Distance calculation for creating adjacency matrix

In [173]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'euclid')
s

array([[0.        , 1.05537273, 0.93912473, ..., 0.84483474, 0.97217577,
        0.98190952],
       [1.05537273, 0.        , 1.12969067, ..., 1.04434628, 1.15789733,
        1.16554428],
       [0.93912473, 1.12969067, 0.        , ..., 0.85361256, 1.0037888 ,
        0.98205711],
       ...,
       [0.84483474, 1.04434628, 0.85361256, ..., 0.        , 0.87827333,
        0.89170957],
       [0.97217577, 1.15789733, 1.0037888 , ..., 0.87827333, 0.        ,
        1.02893614],
       [0.98190952, 1.16554428, 0.98205711, ..., 0.89170957, 1.02893614,
        0.        ]])

In [174]:
X1=pd.DataFrame(s)
X1

,0,1,2,3,4,5,6,7,8,9,...,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599
0,0.000000,1.055373,0.939125,0.881797,0.851384,0.822721,0.958362,0.892930,0.853936,1.025009,...,0.923933,0.881888,0.982011,0.956945,0.920909,0.812360,0.984208,0.844835,0.972176,0.981910
1,1.055373,0.000000,1.129691,1.078747,1.040876,1.035614,1.136298,1.076323,1.044118,1.078794,...,1.083005,1.074728,1.159872,1.147531,1.119000,1.008231,1.151372,1.044346,1.157897,1.165544
2,0.939125,1.129691,0.000000,0.908045,0.912329,0.858236,1.039754,0.951774,0.896485,1.021216,...,0.910098,0.938432,1.006501,0.994696,0.970167,0.816153,0.998182,0.853613,1.003789,0.982057
3,0.881797,1.078747,0.908045,0.000000,0.700468,0.773717,0.942073,0.845445,0.803399,0.961940,...,0.874007,0.843709,0.935460,0.920113,0.872829,0.728835,0.914746,0.771089,0.933010,0.938714
4,0.851384,1.040876,0.912329,0.700468,0.000000,0.746974,0.915665,0.808059,0.759912,0.942647,...,0.866674,0.818868,0.913781,0.902737,0.873596,0.715928,0.907615,0.760448,0.915878,0.920342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,0.812360,1.008231,0.816153,0.728835,0.715928,0.667463,0.857524,0.759128,0.701623,0.899361,...,0.767588,0.748005,0.846246,0.836091,0.788121,0.000000,0.829537,0.669899,0.844076,0.852159
1596,0.984208,1.151372,0.998182,0.914746,0.907615,0.861073,1.032359,0.956823,0.887084,1.043797,...,0.904198,0.837836,1.005385,0.964109,0.959168,0.829537,0.000000,0.854347,0.980219,0.954061
1597,0.844835,1.044346,0.853613,0.771089,0.760448,0.707896,0.904921,0.798101,0.742584,0.919499,...,0.802807,0.785595,0.873591,0.874756,0.826586,0.669899,0.854347,0.000000,0.878273,0.891710
1598,0.972176,1.157897,1.003789,0.933010,0.915878,0.864104,1.040508,0.974476,0.896088,1.057540,...,0.957912,0.923219,1.005307,0.954744,0.973864,0.844076,0.980219,0.878273,0.000000,1.028936
1599,0.981910,1.165544,0.982057,0.938714,0.920342,0.875991,1.034461,0.978682,0.904185,1.082493,...,0.844163,0.854136,1.005209,0.993480,0.967263,0.852159,0.954061,0.891710,1.028936,0.000000

In [175]:
B=np.matrix(X1)
G=nx.from_numpy_matrix(B)

In [176]:
#calculating the mean
mn=np.array(X1)
m=np.nanmean(mn)

In [177]:
threshold = m
G.remove_edges_from([(n1, n2) for n1, n2, w in G.edges(data="weight") if w < threshold])
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

### Construct a graph using stellargraph

In [178]:
from stellargraph import StellarGraph
graph1= StellarGraph.from_networkx(H)
print(graph1.info())

StellarGraph: Undirected multigraph
 Nodes: 1600, Edges: 642755

 Node types:
  default: [1600]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [642755]
        Weights: range=[0.952033, 1.35199], mean=1.02749, std=0.0560901
        Features: none

In [179]:
#getting the  edge list
edge_connnected=list(graph1.edges())
edgesDF = pd.DataFrame(edge_connnected,columns=['source','target'])
edgesDF

        source  target
0            0       1
1            0       6
2            0       9
3            0      13
4            0      15
...        ...     ...
642750    1594    1598
642751    1594    1599
642752    1596    1598
642753    1596    1599
642754    1598    1599

[642755 rows x 2 columns]

In [180]:
from stellargraph.data import BiasedRandomWalk
from stellargraph import StellarGraph
from stellargraph import datasets
from IPython.display import display, HTML

%matplotlib inline

In [181]:
rw = BiasedRandomWalk(graph1)

walks = rw.run(
    nodes=list(graph1.nodes()),  # root nodes
    length=100,  # maximum length of a random walk
    n=10,  # number of random walks per root node
    p=0.5,  # Defines (unormalised) probability, 1/p, of returning to source node
    q=2.0,  # Defines (unormalised) probability, 1/q, for moving away from source node
)
print("Number of random walks: {}".format(len(walks)))
from gensim.models import Word2Vec

str_walks = [[str(n) for n in walk] for walk in walks]
model = Word2Vec(str_walks, size=128, window=5, min_count=0, sg=1, workers=2, iter=1)

Number of random walks: 16000

In [182]:
# The embedding vectors can be retrieved from model.wv using the node ID as key.
model.wv["241"].shape

(128,)

In [183]:
# Retrieve node embeddings and corresponding subjects
node_ids = model.wv.index2word  # list of node IDs

node_embeddings = (
    model.wv.vectors
)  # numpy.ndarray of size number of nodes times embeddings dimensionality
node_targets = node_Class[[int(node_id) for node_id in node_ids]]

In [184]:
node_emb=pd.DataFrame(node_embeddings)

In [185]:
node_tar=pd.DataFrame(node_targets)
node_targets=node_tar.sort_index()

In [186]:
node_emb['Class']=node_targets

### Node embeddings

In [187]:
node_emb

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,Class
0,-0.107341,-0.148704,-0.013684,-0.070516,-0.004752,0.068270,-0.106980,-0.206946,-0.057863,-0.093920,...,0.000532,-0.040412,-0.273380,0.086619,0.091931,0.091417,0.062059,0.046272,0.026364,1
1,-0.107350,-0.142792,-0.028644,-0.068256,-0.003788,0.074551,-0.113905,-0.207251,-0.056186,-0.109538,...,-0.007854,-0.037439,-0.273691,0.083018,0.084654,0.097257,0.060008,0.071033,0.031662,1
2,-0.106554,-0.156439,-0.029438,-0.066539,-0.004516,0.081343,-0.109971,-0.202093,-0.055702,-0.107318,...,-0.000748,-0.036007,-0.284847,0.090080,0.099928,0.098443,0.058460,0.071255,0.028579,1
3,-0.103334,-0.155213,-0.023325,-0.068571,-0.003706,0.065404,-0.105798,-0.198328,-0.050723,-0.096812,...,0.004612,-0.040843,-0.275160,0.088483,0.094560,0.091672,0.054142,0.050803,0.031553,1
4,-0.110609,-0.165490,-0.013442,-0.060349,-0.003637,0.072785,-0.112406,-0.192517,-0.049591,-0.096488,...,0.007146,-0.048230,-0.277060,0.083346,0.095243,0.092267,0.058005,0.042425,0.036501,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,-0.091727,-0.110138,0.025831,-0.125204,0.067710,-0.065656,-0.154081,-0.229601,-0.074932,-0.131811,...,0.030570,-0.055535,-0.195187,0.051126,0.028187,0.074083,0.057648,0.005618,-0.015781,0
1596,-0.093989,-0.112040,0.031964,-0.127211,0.068720,-0.070885,-0.150367,-0.228051,-0.074207,-0.126990,...,0.026580,-0.058177,-0.202025,0.052767,0.034354,0.076679,0.057514,0.001526,-0.013338,0
1597,-0.098705,-0.108924,0.030214,-0.127943,0.070014,-0.070256,-0.152879,-0.240127,-0.071998,-0.135340,...,0.029686,-0.059843,-0.202972,0.055548,0.032000,0.075697,0.063089,0.001215,-0.012975,0
1598,-0.096059,-0.111659,0.031928,-0.126766,0.071097,-0.073538,-0.152892,-0.233154,-0.071073,-0.125136,...,0.025270,-0.056811,-0.204969,0.051064,0.035774,0.076428,0.056002,-0.000048,-0.011223,0
1599,-0.065537,-0.078423,0.023374,-0.083689,0.049948,-0.046615,-0.106887,-0.160023,-0.052063,-0.082154,...,0.017859,-0.036370,-0.140828,0.037984,0.023061,0.050043,0.042095,0.002222,-0.005720,0

In [188]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns

In [189]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

### CROSS VALIDATION

In [190]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
cv = KFold(n_splits=10, random_state=1, shuffle=True)
kf = KFold(n_splits=10)

In [191]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
scores = cross_val_score(lsvm, X, Y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.645

In [192]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
scores = cross_val_score(pa, X, Y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.6174999999999999

In [193]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression(max_iter=10000) 
scores = cross_val_score(log, X, Y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.545625

In [194]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300)
scores = cross_val_score(rf, X, Y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.943125

In [195]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
scores = cross_val_score(xgbc, X, Y, cv=cv, n_jobs=-1)
print(np.mean(scores))

0.9412499999999999

### Baseline models

In [196]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=y)

In [197]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[  5 155]
 [  0 160]]
              precision    recall  f1-score   support

           0       1.00      0.03      0.06       160
           1       0.51      1.00      0.67       160

    accuracy                           0.52       320
   macro avg       0.75      0.52      0.37       320
weighted avg       0.75      0.52      0.37       320

accuracy_score:  0.515625

In [198]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[122  38]
 [ 77  83]]
              precision    recall  f1-score   support

           0       0.61      0.76      0.68       160
           1       0.69      0.52      0.59       160

    accuracy                           0.64       320
   macro avg       0.65      0.64      0.64       320
weighted avg       0.65      0.64      0.64       320

accuracy_score:  0.640625

In [199]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[152   8]
 [ 10 150]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.94       160
           1       0.95      0.94      0.94       160

    accuracy                           0.94       320
   macro avg       0.94      0.94      0.94       320
weighted avg       0.94      0.94      0.94       320

accuracy_score:  0.94375

In [200]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[152   8]
 [  8 152]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       160
           1       0.95      0.95      0.95       160

    accuracy                           0.95       320
   macro avg       0.95      0.95      0.95       320
weighted avg       0.95      0.95      0.95       320

accuracy_score:  0.95

In [201]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[97 63]
 [77 83]]
              precision    recall  f1-score   support

           0       0.56      0.61      0.58       160
           1       0.57      0.52      0.54       160

    accuracy                           0.56       320
   macro avg       0.56      0.56      0.56       320
weighted avg       0.56      0.56      0.56       320

accuracy_score:  0.5625